# Generated by Django 5.2.2 on 2025-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.CharField(choices=[('O', 'Ocean'), ('L', 'Lake'), ('R', 'River'), ('P', 'Pond'), ('C', 'Creek')], default=0, max_length=1)),
                ('water', models.CharField(choices=[('F', 'Fresh Water'), ('S', 'Salt Water')], default=0, max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('weather', models.CharField(choices=[('S', 'Sunny'), ('C', 'Cloudy'), ('R', 'Rainy'), ('T', 'Thunder'), ('W', 'Windy'), ('F', 'Foggy')], default=0, max_length=20)),
            ],
        ),
    ]
