# Generated by Django 5.2.2 on 2025-06-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.trip'),
        ),
    ]
