# Generated by Django 5.2.2 on 2025-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_location_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.IntegerField(max_length=5)),
                ('bait', models.CharField(choices=[('W', 'Worms'), ('S', 'Shrimp'), ('C', 'Cutbait'), ('M', 'Minow'), ('C', 'Crawfish'), ('L', 'Lure')], default=0, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(verbose_name='Date Of Trip'),
        ),
    ]
