# Generated by Django 5.2.2 on 2025-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_fish_alter_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
